### ISSUE TITLE
figure out a way to show how input and output is connected to Activity and not just Plan

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/renku-aqs-graph-library#6]

**Comment by burnout87** [comment]
Thanks to the example in https://renkulab.io/projects/rok.roskar/lineage-demo/files/blob/notebooks/provenance-graphs.ipynb (thanks @rokroskar ) inputs and outputs are directly connected to an `Activity` node. For now, I also removed from the output the `Plan` (ie `Action`) node, but we can decide that we still want it, perhaps when implementing #5 , we can re-introduce it.

![image](https://user-images.githubusercontent.com/3757833/213242644-8032ab61-2d6f-4f5c-94a6-9003a2c8659a.png)

**Comment by burnout87** [comment]
This has been implemented completely on the [JS library](https://github.com/oda-hub/renku-aqs-graph-library/)
