### ISSUE TITLE
do the sparql query (currently in the plugin) in JS communica

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/renku-aqs-graph-library#8]
do the sparql query (currently in the plugin) in JS communica. 

the query content should be part of the config.

two approaches are possible:

* communica query static ttl file fetched by URL  - can be served by the same jupyter server extension which serves html in the plugin
* communica queries specialized sparql endpoint on jupyter server extension, which implements sparql query with rdflib

**Comment by burnout87** [comment]
With [this](https://github.com/oda-hub/renku-aqs/pull/38), parts of the query are now provided with the config and built when the page is loaded.

Regarding the loading of the `ttl` file, this is still provided directly onto the output html file, the two ideas here proposed will be explored.

**Comment by burnout87** [comment]
Also the loading of the `ttl` data now happens by querying the jupyter server extension
